apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dornoc-v3
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm-charts/dornoc-v3
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false