---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helm-sources
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/mehdihasan/fleet-infra
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dornoc-v3
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm-charts/dornoc-v3
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: helm-sources
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dornoc-v4
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm-charts/dornoc-v4
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: helm-sources
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false