apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: dornoc-service-{{ .Values.version }}
  labels:
    app: dornoc-{{ .Values.version }}
spec:
  ports:
  - port: 6000
    targetPort: 5000
  selector:
    app: dornoc-{{ .Values.version }}
