apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: mopo
  name: dornoc-deployment-{{ .Values.version }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dornoc-{{ .Values.version }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dornoc-{{ .Values.version }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: dornoc-config-{{ .Values.version }}
        - secretRef:
            name: dornoc-secret
        image: {{ .Values.deploy.image }}:{{ .Values.deploy.tag }}
        imagePullPolicy: IfNotPresent
        name: dornoc
        ports:
        - containerPort: 5000
          name: 5000tcp2
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30